#!/usr/bin/env node
// MOCK-ONLY. Builds app/mock/data.js from the lead's real files, read in place and never changed:
//   data/schools.json (a subset of real school rows) and the saved NLSchools status fragments in data/samples/.
// The rows are copied verbatim (same text-extraction rules as API.md §0) so the mock shows real words.
// Usage: node app/mock/build.mjs
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const REPO = fileURLToPath(new URL('../../', import.meta.url))
const read = (p) => readFileSync(REPO + p, 'utf8')

// API.md §0 text extraction (mock-build copy).
const NAMED = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
  ndash: '–',
  mdash: '—',
  lsquo: '‘',
  rsquo: '’',
  ldquo: '“',
  rdquo: '”',
  hellip: '…',
  eacute: 'é',
  egrave: 'è',
  agrave: 'à',
  ecirc: 'ê',
  ccedil: 'ç',
  ocirc: 'ô',
  icirc: 'î',
  laquo: '«',
  raquo: '»',
}
const normText = (s) =>
  String(s)
    .replace(/[\s ]+/g, ' ')
    .trim()
const decodeEntities = (s) =>
  s.replace(/&(#x[0-9a-f]+|#\d+|[a-z]+);/gi, (m, e) => {
    if (e[0] === '#') {
      const n = e[1] === 'x' || e[1] === 'X' ? parseInt(e.slice(2), 16) : parseInt(e.slice(1), 10)
      return Number.isFinite(n) ? String.fromCodePoint(n) : m
    }
    return NAMED[e] ?? m
  })
const extractText = (body) =>
  normText(
    decodeEntities(
      decodeEntities(
        body
          .replace(/<script[\s\S]*?<\/script>/gi, ' ')
          .replace(/<style[\s\S]*?<\/style>/gi, ' ')
          .replace(/<!--[\s\S]*?-->/g, ' ')
          .replace(/<!\[CDATA\[([\s\S]*?)\]\]>/g, '$1')
          .replace(/<[^>]*>/g, ' '),
      ),
    ),
  )

function parseRows(file) {
  const body = read(file)
  const tbody = body.slice(body.indexOf('<tbody>'), body.indexOf('</tbody>'))
  return tbody
    .split(/<tr /)
    .slice(1)
    .map((chunk) => {
      const tr = '<tr ' + chunk.slice(0, chunk.indexOf('</tr>') + 5)
      const row_id = /id=['"]?([^'"\s>]+)/.exec(tr)[1]
      const cells = [...tr.matchAll(/<td([^>]*)>([\s\S]*?)<\/td>/g)]
      const [c1, c2, c3, c4, c5] = cells
      const brAt = c1[2].indexOf('<br/>')
      return {
        row_id,
        school_text: extractText(/<span[^>]*>([\s\S]*?)<\/span>/.exec(c1[2])[1]),
        community_text: extractText(c1[2].slice(brAt + 5)) || null,
        status_class: /class='([^']*)'/.exec(c2[1])[1].split(/\s+/)[0],
        status_text: extractText(c2[2]),
        quote: extractText(c3[2]),
        family_text: extractText(c4[2]),
        region_text: extractText(c5[2]),
        source_text: extractText(tr),
      }
    })
}

const page = extractText(read('data/samples/nlschools/statusreport-2026-09-14T1408NDT.html'))
const OPEN_RULE = 'If your school is not listed below, the status is normal and open as usual.'
if (!page.includes(OPEN_RULE)) throw new Error('open rule not found in the saved page')
const LIST_DATE_TEXT = /Real-time school closure information for: ([A-Z][a-z]+day, [A-Z][a-z]+ \d{1,2}, \d{4})/.exec(page)[1]

const rows = {
  today: parseRows('data/samples/nlschools/schoolstatus-2026-09-14T1640Z.html'),
  storm: parseRows('data/samples/wayback/schoolstatus-20240110005921.html'),
}

const schoolsFile = JSON.parse(read('data/schools.json'))
const all = schoolsFile.schools
const IDS = [
  // The six schools in the real rows.
  'nls-300422',
  'nls-200498',
  'nls-300407',
  'nls-400240',
  'nls-400430',
  'nls-400371',
  // Central (with the four above from the real rows: 12 in all).
  'nls-300180',
  'nls-300132',
  'nls-400235',
  'nls-300480',
  'nls-300414',
  'nls-300417',
  'nls-300418',
  'nls-300495',
  // Western (with Eastside: 4).
  'nls-200060',
  'nls-200485',
  'nls-200389',
  // Avalon and Labrador.
  'nls-400265',
  'nls-400497',
  'nls-100008',
  'nls-200046',
  // All six CSFP schools.
  'csfp-500460',
  'csfp-500499',
  'csfp-500472',
  'csfp-500459',
  'csfp-500095',
  'csfp-500107',
  // Private, Indigenous and Other.
  'private-anchor-academy',
  'private-st-bonaventures-college',
  'indigenous-sheshatshiu-innu-school',
  'other-murphy-centre',
]
const schools = IDS.map((id) => {
  const s = all.find((x) => x.id === id)
  if (!s) throw new Error(`no school ${id}`)
  const { source_row, urban_rural, ...rest } = s
  return rest
})

const out = `// GENERATED by app/mock/build.mjs. MOCK-ONLY. Do not edit by hand.
// Real school rows copied from data/schools.json, and real NLSchools status rows extracted verbatim from
// data/samples/ (the mock marks them sample: true, API.md §0).
export const OPEN_RULE = ${JSON.stringify(OPEN_RULE)}
export const LIST_DATE_TEXT_2026_09_14 = ${JSON.stringify(LIST_DATE_TEXT)}
export const REAL_ROWS = ${JSON.stringify(rows, null, 2)}
export const SCHOOLS = ${JSON.stringify(schools, null, 2)}
// The whole provincial list's counts and origins (from data/schools.json), for the Sources page.
export const COUNTS = ${JSON.stringify(schoolsFile.counts, null, 2)}
export const SCHOOL_SOURCES = ${JSON.stringify(schoolsFile.sources, null, 2)}
`
writeFileSync(fileURLToPath(new URL('./data.js', import.meta.url)), out)
console.log(`app/mock/data.js: ${schools.length} schools, rows today ${rows.today.length}, storm ${rows.storm.length}`)
