#!/usr/bin/env node
// node scripts/gen-schools.mjs
// data/schools.json (lead-owned) → core/schools-data.js, so core runs in workerd without reading files.
// core/tests/schools.test.mjs checks the two are equal.
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const ROOT = fileURLToPath(new URL('..', import.meta.url))
const data = JSON.parse(readFileSync(ROOT + 'data/schools.json', 'utf8'))
const out = `// GENERATED by scripts/gen-schools.mjs from data/schools.json. Do not edit: run the script.
export const SCHOOLS_DATA = ${JSON.stringify(data, null, 1)}
`
writeFileSync(ROOT + 'core/schools-data.js', out)
console.log(`core/schools-data.js: ${data.schools.length} schools`)
